### PR TITLE
Fix Mesh Search

### LINKED ISSUE #3419: Using Mesh Term as My Repors predicate throws error
building a report along the lines of "get all XXX associated with the MeSH term ZZZ" throws the following error:
```
ilios-07af94bbfd8694db87aad03f5c42ab08.js:2843 Error: a glimmer transaction was begun, but one already exists. You may have a nested transaction
    at e.assert (vendor-f2e927e04b8abbbc4d500c718a23a4e3.js:2356)
    at i.e.begin (vendor-f2e927e04b8abbbc4d500c718a23a4e3.js:2264)
    at i.begin (vendor-f2e927e04b8abbbc4d500c718a23a4e3.js:2825)
    at n.e._renderRoots (vendor-f2e927e04b8abbbc4d500c718a23a4e3.js:2956)
    at n.e._renderRootsTransaction (vendor-f2e927e04b8abbbc4d500c718a23a4e3.js:2961)
    at n.e._revalidate (vendor-f2e927e04b8abbbc4d500c718a23a4e3.js:2963)
    at e.invokeWithOnError (vendor-f2e927e04b8abbbc4d500c718a23a4e3.js:2390)
    at e.flush (vendor-f2e927e04b8abbbc4d500c718a23a4e3.js:2377)
    at e.flush (vendor-f2e927e04b8abbbc4d500c718a23a4e3.js:2393)
    at e.end (vendor-f2e927e04b8abbbc4d500c718a23a4e3.js:2401)
```

hard refresh is required to clear the form and move forward.

### PR DESCRIPTION
**Pull request by jrjohnson**
Mesh search was broken when no terms were provided as it was expecting
an array. (broken in #3395 [4a5fa1e3509932a0ed6917583ee136d7eb885b64]).

Fixes #3419

### CODE REVIEW

**Comment by jrjohnson** [comment]
Deploy preview ready!

Built with commit 10267cba588a4777f3161170e80ff029f98f859b

https://deploy-preview-3423--ilios-frontend.netlify.com
